services:
  provide-user-interface:
    image: ghcr.io/data-space-core/provide-user-interface/stage:latest
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .env:/app/.env
    ports:
      - "8000:8000"